services:

  radicale:
    image: cupcakearmy/radicale:latest
    container_name: radicale
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/data
    ports:
      - "5232:5232"
